### ISSUE TITLE
Possible Error in shooter.java

### ISSUE THREAD

**Issue by Crossle86** [ORF-4450/Robot24#11]
In shooter.java is the following method:
    /**
     * Get the average wheel speed of top and bottom
     * shooter rollers
     * @return the mean wheel speed in meters per second
     */
    public double getWheelSpeed() {
        double wheelRadius = 1.5 * 0.0254; // 1.5 in -> meters
        double topWheelSpeed = (Math.abs(topMotorEncoder.getVelocity()) / 60.0) * wheelRadius * 2 * Math.PI; // rpm -> m/s
        double bottomWheelSpeed = (Math.abs(bottomMotorEncoder.getVelocity()) / 60.0) * wheelRadius * 2 * Math.PI; // rpm -> m/s
        double averageWheelSpeed = 0.2 * (topWheelSpeed + bottomWheelSpeed); // mean of top and bottom
        return averageWheelSpeed;
    }

First the doc uses both "average" and "mean". Should choose one.
Second, in the averageWheelSpeed calculation, shouldn't 0.2 be 0.5?

**Comment by cole-wilson** [comment]
Correct, the 0.2 is technically a mistake. However, it is possible that this is intentionally lower than 0.5 as a sort of arbitrary tuning constant. It may be one of those things that just worked better for some reason. This code only relates to the "shoot while moving" part of the shoot code.

I use mean and average interchangeably, so they are referring to the same thing.

**Comment by Crossle86** [comment]
I would argue that even though those terms refer to the same thing, it is not good form to use both in such close proximity. It is less clear than using one or the other exclusively in this snippet of documentation.

It would be good to know for sure if the .2 is an error or a tuning adjustment. I expect we will leave fixing it to after Girls Gen.

**Comment by cole-wilson** [comment]
Understood. I made a `Girls-Gen` branch for future changes.

**Comment by cole-wilson** [comment]
@Crossle86 I've thought about the 0.2 a lot, and I've decided that while it probably was just an error, it has become a tuning constant purely because that is what we ran with. I suggest keeping it but rewriting it to `0.4 * 0.5 * ...` for clarity.
